name: 03-basics-relation
tables:
  - name: Country
    columns:
      - name: code
        primary: true
      - name: name
    storage:
      path: countries.properties
  - name: Customer
    columns:
      - name: email
        primary: true
      - name: firstName
      - name: lastName
      - name: countryCode
        reference: Country
    storage:
      path: customer.csv
views:
  - name: CustomerWithCountry
    query: >
      SELECT Customer.lastName as "Last Name", Customer.firstName as "First Name", Country.name as "Country"
      FROM Customer
      LEFT OUTER JOIN Country
        ON Country.code = Customer.countryCode
      ORDER BY Customer.lastName
