name: 01-basics-views
tables:
  - name: Customer
    columns:
      - name: email
      - name: firstName
      - name: lastName
      - name: countryCode
    storage:
      path: customer.csv
  - name: Country
    columns:
      - name: code
      - name: name
    storage:
      path: countries.properties
views:
  - name: UserWithCountry
    query: >
      SELECT User.lastName as "Last Name", User.firstName as "First Name", Country.name as "Country"
      FROM User
      LEFT OUTER JOIN Country
        ON Country.code = User.countryCode
      ORDER BY User.lastName
