name: 01-basics-views
tables:
  - name: Customer
    columns:
      - name: email
      - name: firstName
      - name: lastName
      - name: countryCode
    storage:
      uri: customer.csv
  - name: Country
    columns:
      - name: code
      - name: name
    storage:
      uri: countries.properties
views:
  - name: CustomerWithCountry
    query: >
      SELECT Customer.lastName as "Last Name", Customer.firstName as "First Name", Country.name as "Country"
      FROM Customer
      LEFT OUTER JOIN Country
        ON Country.code = Customer.countryCode
      ORDER BY Customer.lastName
